//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManager.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EquipmentManagerEntities : DbContext
    {
        public EquipmentManagerEntities()
            : base("name=EquipmentManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<PartNumber> PartNumbers { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<UnitsOfMeasure> UnitsOfMeasures { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Installation> Installations { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<EquipmentLabour> EquipmentLabours { get; set; }
        public virtual DbSet<EquipmentModule> EquipmentModules { get; set; }
        public virtual DbSet<PartCategory> PartCategories { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<EquipmentPart> EquipmentParts { get; set; }
    }
}
