//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentItem
    {
        public EquipmentItem()
        {
            this.InstallationEquipmentItems = new HashSet<InstallationEquipmentItem>();
        }
    
        public int Id { get; set; }
        public int EquipmentId { get; set; }
        public int ItemId { get; set; }
        public double QuantityRequired { get; set; }
        public double QuantityRequiredSpare { get; set; }
        public string UnitOfMeasure { get; set; }
        public string Notes { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Item Item { get; set; }
        public virtual ICollection<InstallationEquipmentItem> InstallationEquipmentItems { get; set; }
    }
}
