//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallationEquipmentItemStatus
    {
        public InstallationEquipmentItemStatus()
        {
            this.InstallationEquipmentItems = new HashSet<InstallationEquipmentItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<InstallationEquipmentItem> InstallationEquipmentItems { get; set; }
    }
}
