//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallationEquipmentLabour
    {
        public int Id { get; set; }
        public int InstallationId { get; set; }
        public int EquipmentLabourId { get; set; }
        public LabourStatus LabourStatusId { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<TemporalUnit> QuantityUnit { get; set; }
        public Nullable<decimal> CostPerUnit { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
    
        public virtual EquipmentLabour EquipmentLabour { get; set; }
        public virtual Installation Installation { get; set; }
    }
}
