//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallationEquipmentPart
    {
        public int Id { get; set; }
        public int InstallationModuleId { get; set; }
        public int EquipmentPartId { get; set; }
        public Nullable<System.DateTime> DateQuoted { get; set; }
        public Nullable<System.DateTime> DateOrdered { get; set; }
        public Nullable<System.DateTime> DateExpected { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public int StatusId { get; set; }
        public Nullable<decimal> CostPerUnit { get; set; }
        public Nullable<double> UnitsOrdered { get; set; }
        public Nullable<decimal> Postage { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
    
        public virtual EquipmentPart EquipmentPart { get; set; }
        public virtual InstallationEquipmentModule InstallationEquipmentModule { get; set; }
    }
}
