//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallationEquipmentModule
    {
        public InstallationEquipmentModule()
        {
            this.InstallationEquipmentLabours = new HashSet<InstallationEquipmentLabour>();
            this.InstallationEquipmentParts = new HashSet<InstallationEquipmentPart>();
            this.SubordonateModules = new HashSet<InstallationEquipmentModule>();
        }
    
        public int Id { get; set; }
        public int EquipmentModuleId { get; set; }
        public int InstallationId { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
        public Nullable<int> ParentModuleId { get; set; }
    
        public virtual EquipmentModule EquipmentModule { get; set; }
        public virtual ICollection<InstallationEquipmentLabour> InstallationEquipmentLabours { get; set; }
        public virtual Installation Installation { get; set; }
        public virtual ICollection<InstallationEquipmentPart> InstallationEquipmentParts { get; set; }
        public virtual ICollection<InstallationEquipmentModule> SubordonateModules { get; set; }
        public virtual InstallationEquipmentModule ParentModule { get; set; }
    }
}
