//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallationEquipmentItem
    {
        public InstallationEquipmentItem()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public int InstallationId { get; set; }
        public int EquipmentItemId { get; set; }
        public Nullable<System.DateTime> DateOrdered { get; set; }
        public Nullable<System.DateTime> DateExpected { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<int> StatusId { get; set; }
        public decimal CostPerUnit { get; set; }
        public double UnitsOrdered { get; set; }
        public decimal Postage { get; set; }
    
        public virtual EquipmentItem EquipmentItem { get; set; }
        public virtual Installation Installation { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
