//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Items1 = new HashSet<Item>();
            this.PartNumbers = new HashSet<PartNumber>();
            this.EquipmentItems = new HashSet<EquipmentItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public decimal ItemsPerUnit { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Link { get; set; }
        public bool Obsolete { get; set; }
        public Nullable<int> ReplacedBy_Id { get; set; }
    
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ICollection<Item> Items1 { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<PartNumber> PartNumbers { get; set; }
        public virtual ICollection<EquipmentItem> EquipmentItems { get; set; }
    }
}
