//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int InstallationEquipmentItemId { get; set; }
        public System.DateTime DateOrdered { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public double Quantity { get; set; }
        public string Notes { get; set; }
    
        public virtual InstallationEquipmentItem InstallationEquipmentItem { get; set; }
    }
}
