//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartNumber
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
