//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManager.Data
{
    using System;
    
    public enum TemporalUnit : int
    {
        Hour = 0,
        Day = 1,
        Week = 2,
        Month = 3,
        Year = 4
    }
}
