//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManager.Data
{
    using System;
    
    public enum TemporalUnit : int
    {
        Hours = 0,
        Days = 1,
        Weeks = 2,
        Months = 3,
        Years = 4
    }
}
